---
conditions: v1
stages:
  - name: check
  - name: basic-tests

sudo: required
dist: ubuntu
language: python

branches:
  only:
    - master

install:
  - bash
  - python3 -m pip install -r requirements.txt

# command to run tests
script:
  - bash test.sh
 