language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- pytest
env:
  global:
  - secure: VAd9GqnYD4LYSQSXitLf97YHeJ6nUHh6WTHiRrato0s+K8y9X8Gpt86A+GRqv/4CaW55PwpN7yEkMZFKcSQp/XHwQarvDUP+BPA0oggXxgcNXedVimWTzbssQjoF8mEbE9m8dZnh85LqlX5id7CFjBznocpEl8V0IWWq1PrSnIOCBHM7/lG53aI7Lk2rZjpX+R2vsGUQiYRaS2gysvI3wb2xcr5n4eA3E8iIRNoA/jtiBQe6+aEihROz+d/vLyz285PBcMCMx2FpGPKyPhO1se0aOJ9sagnDkKj3C/cUDm5MftB+0fvvUaw4ywarRfzt1GNRbvPYsdHarIk4inCDUt8BxAYVoWJ8w2FwEyD3uCIkYTYzvXrzWVS2QB96r27dObwVy5d25K938R93zZT/zrVC7mwxtqUdVaYoA5WbmuCU28/PIhelA+hR9c6LGhpLADZQzUc7ropoEyEzP5AaVoqx9GXrNr12Z0772S8gNwYZdpf9GkbwRT0SQ3xUi/Erm2gWIYnbbHS87SeUd2mmReih8j7wDwZmjhJWeneNot0E2GRJn/kjJlp99kyagFdNCu/sBzoG8cuYa7EkK9gP8MRqinr/R4Z3+dp4Mv6zH8XwnKEyJaHUXXsj4ObdAuMFxRI4q3aHDanGvcF1SVsKAWqJU6C9kBitroqNNKrVOsk=
