openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"
servers:
  - url: http://localhost:5000

paths:
  /users:
    post:
      summary: Crear un usuario
      description: Crea un usuario en base a los datos de id y nombre ingresados por parametro.
      operationId: app.create_user
      responses:
        200:
          description: Usuario creado con exito
      parameters:
        - name: id
          in: path
          description: Name of the person to greet.
          required: true
          schema:
            type: string
            example: "dave"
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          schema:
            type: string
            example: "dave"

    get:
      summary: Extraer la información
      description: Se extrae información todos los usuarios de la base de datos.
      operationId: app.read_user
      responses:
        200:
          description: Datos obtenidos con éxito
          content:
            text/plain:
              schema:
                type: string
                example: '[{"_id": {"$oid": "5dcb7fc020f273c7abeb0a7b"}, "id": "1", "name": "Johnatan"}]'