openapi: 3.0.0
info:
  title: Distributed Systems OpenApi
  description: Distributed Systems Api Documentation
  version: '0.1'
servers:
  - url: 'http://localhost:4000'
paths:
  /users:
    post:
      description: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
            examples:
              '0':
                value: "{\n\t\"name\": \"Sandra\",\n\t\"lastname\": \"Nino\",\n\t\"idnumber\": 1143874329\n}"
      responses:
        '201':
          description: User succesfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
              examples:
                '0':
                  value: "{\n\t\"message\": \"A new user has been created\",\n\t\"user\": {\n\t\t\"name\": \"Sandra\",\n\t\t\"lastname\": \"Nino\",\n\t\t\"idnumber\": 1143874328, \n\t\t\"_id\": \"5dc9fd0257e5234a10c68edc\"\n\t\t}\n}"
        '400':
          description: Error:Trying to create a user with an existing idnumber
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                '0':
                  value: "{\n\t\"message\": \"A user has been created with that number\"\n}"
        '500':
          description: If exists another error in the service
  
    get:
      description: Retrieve all users
      responses:
        '200':
          description: List of all users or a message if there isn´t any user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
              examples:
                '0':
                  value: "{\n\t\"message\": \"A list of all users\",\n\t\"users\": [ \n\t    {\n\t\t\"name\": \"Sandra\",\n\t\t\"lastname\": \"Nino\",\n\t\t\"idnumber\": 1143874328, \n\t\t\"_id\": \"5dc9fd0257e5234a10c68edc\"\n\t    },\n\t    {\n\t\t\"name\": \"Daniel\",\n\t\t\"lastname\": \"Quintero\",\n\t\t\"idnumber\": 1143874329, \n\t\t\"_id\": \"5dc9fd0257e5234a10c68edd\"\n\t    }\n\t[\n}"
                '1':
                  value: "{\n\t\"message\": \"List of users is empty\"\n}"
                  
        '500':
          description: If exists an error in the service
          
components:
  schemas:
    UserRequest:
      type: object
      properties:
        idnumber: 
          type: integer
        name:
          type: string
        lastname:
          type: string
    User:
      type: object
      properties:
        idnumber: 
          type: integer
        name:
          type: string
        lastname:
          type: string
        _id:
          type: string
    Response:
      type: object
      properties:
        message:
          type: string
        user:
          $ref: "#/components/schemas/User"
    Error:
      type: object
      properties:
        message:
          type: string
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"