swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/"

# Paths supported by the server application
paths:
  /users:
    get:
      operationId: "users.read"
      tags:
        - "Users"
      summary: "Get all the users"
      description: "Get all the GitHub users from the database"
      responses:
        200:
          description: "Successful read of all the users"
          schema:
            type: "array"
            items:
              properties:
                name:
                  type: "string"
                numRepos:
                  type: "integer"
  /users/{name}:
    parameters:
      - name: name
        in: path
        required: true
        type: string
        format: path
    post:
      operationId: "users.insert"
      tags:
        - "Users"
      summary: "Insert a new user"
      description: "Insert a new GitHub user into the database"
      responses:
        200:
          description: "Successful add the new user"
          schema:
            properties:
              id:
                type: "string"
              

