openapi: 3.0.0
info:
  title: User API
  version: 0.2.0
paths:
  "/users/":
    get:
      operationId: handlers.get_users
      summary: Returns user information.
      responses:
        "200":
          description: Successful response.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/User"

  "/users/{username}":
    get:
      operationId: handlers.get_user
      summary: Returns the user info.
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
            format: path
      responses:
        "200":
          description: Successful response.
          content:
            "*/*":
              schema:
                type: "array"
                items:
                  properties:
                    id:
                      type: "string"
                    username:
                      type: "integer"

  "/users/insert/{username}":
    get:
      operationId: handlers.insert_user
      summary: Inserts an user.
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
            format: path
      responses:
        "201":
          description: Successful response.
          content:
            "*/*":
              schema:
                type: "array"
                items:
                  properties:
                    id:
                      type: "string"
                    username:
                      type: "integer"
        "400":
          description: "Bad Request"

  "/users/delete/{username}":
    get:
      operationId: handlers.delete_user
      summary: Deletes an user.
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
            format: path
      responses:
        "200":
          description: Successful response.
        "400":
          description: "Bad Request"

components:
  schemas:
    User:
      type: "array"
      required:
        - id
        - username
      properties:
        id:
          type: integer
          description: User id
          example: 123
        username:
          type: string
          description: User name
          example: juan
        